substitutions:

  # **** CHANGE FRIENDLY NAME TO SOMETHING UNIQUE PER DEVICE ****
  friendly_name: Kauf Plug


esphome:

  # **** CHANGE DEVICE NAME TO SOMETHING UNIQUE PER DEVICE ****
  name: kauf-plug     # **** RENAME YAML FILE TO SAME NAME ****

  platform: ESP8266
  board: esp01_1m

  esp8266_restore_from_flash: true

  # remove next line if renaming to something unique above
  name_add_mac_suffix: true


  project:
    name: "kauf.plf10"
    version: "1.7"


  on_boot:
    then:
        # wait until ESPHome tries loading wifi credentials
      - wait_until:
          lambda: 'return ( wifi_wificomponent->tried_loading_creds );'


      - if:
          condition: # don't do anything if credentials were loaded unless force_ap is on as override
            lambda: 'return ( wifi_wificomponent->loaded_creds && !id(force_ap) );'
          then:
            - logger.log: "------------------->>>>>>>>>>>>>>>>>   already has wifi configured, leaving ap timeout cranked"
          else:      # if credentials not loaded or force_ap is set, lower ap timeout to allow saving new credentials
            - logger.log: "------------------->>>>>>>>>>>>>>>>>   wifi not configured, enabling ap and waiting"

              # set ap timeout to 15 seconds in milliseconds.
            - lambda: |- 
                wifi_wificomponent->set_ap_timeout(15000);  
            - wait_until:
                wifi.connected
            - logger.log: "------------------->>>>>>>>>>>>>>>>>   wifi connected, cranking ap timeout back up"
            - globals.set:  # clear global 
                id: force_ap
                value: 'false'
              # set ap timeout to max 32 bit value in milliseconds.  About 3.5 weeks.
            - lambda: |-
                wifi_wificomponent->set_ap_timeout(2147483647);  


globals:
  - id: force_ap
    type: bool
    restore_value: yes
    initial_value: "true"


wifi:

  # default credentials as backup.  Also needed to show found networks in captive portal.
  ssid: initial_ap2
  password: asdfasdfasdfasdf

  # Uncomment below to set a static IP
  # manual_ip:
  #   static_ip: !secret kauf_bulb_ip_address
  #   gateway: !secret wifi_gateway
  #   subnet: !secret wifi_subnet
  #   dns1: !secret wifi_dns1

  # use_address allows wireless programming through dashboard.  remove after programming.
  # use_address: 192.168.1.3

  # default is 20, 17 is recommended.
  output_power: 17


  ap:
    ssid: ${friendly_name} Hotspot
    ap_timeout: 2147483647ms        # default to max 32-bit value in milliseconds.  About 3.5 weeks.


captive_portal:   # for fallback wifi hotspot

logger:                               # Enable logging
#  baud_rate: 0                       # Disable UART logging since TX pad not easily available

api:                                  # Enable Home Assistant API
  # password: !secret api_password    # optional password field for Home Assistant API.

ota:
  # password: !secret ota_password    # optional password for OTA updates.

debug:                                # outputs additional debug info when logs start


web_server:                           # web server allows access to device with a web browser
  # auth:                             # optional login details for web interface
  #   username: admin
  #   password: !secret web_server_password

  # host css and js file directly on device
  css_include: "z_includes/webserver-v1.min.css"
  css_url: ""
  js_include: "z_includes/webserver-v1.min.js"
  js_url: ""


# red led, blink when not connected to wifi or Home Assistant
status_led:
    pin:
      number: GPIO0
      inverted: true

  
binary_sensor:  

    # button input toggles relay and thereby blue led
  - platform: gpio
    id: button
    name: Kauf Plug Button
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: true

    on_click:

      - min_length: 30ms
        max_length: 2s
        then:
          - if:
              condition: # only toggle relay if button is enabled
                lambda: 'return (id(select_button).state == "Enabled");'
              then:
                switch.toggle: relay



        # restart with AP enabled if button is held for 5 seconds (up to 30 seconds because ESPHome requires a max).
        # Not disabled by button disable option because you may not be able to re-enable button if wifi is not connecting.
        # If your kid accidentally triggers this, the plug will just reboot and reconnect to wifi.  Shouldn't harm anything.

        # we have to restart because ESPHome's AP won't show the captive portal once wifi connects.
      - min_length: 5s
        max_length: 30s
        then:
          - logger.log: "------------------->>>>>>>>>>>>>>>>>   HELD BUTTON 5 SECONDS, FORCING AP"
  
          # blink LED for 10s then restart to get captive portal to turn on.
          - globals.set:
              id: force_ap
              value: 'true'
          - script.execute: blink_led
          - delay: 10s
          - switch.turn_on: restart_switch


    # indicates whether plugged-in devices is running based on configurable threshold.
  - platform: template
    id: in_use
    name: ${friendly_name} Device In Use


# blink LED forever.  Used when button is held to re-enable AP.  Stops blinking because plug restarts.
script:
  - id: blink_led
    mode: queued
    then:
      - switch.toggle: blue_led
      - delay: 333ms
      - script.execute: blink_led
  - id: clear_wifi_script
    then:
      - lambda: |-
          wifi_wificomponent->clear_stored_creds();  
      - delay: 2s
      - switch.turn_on: restart_switch
    

switch:    

    # blue LED follows relay power state
  - platform: gpio
    id: blue_led
    pin:
      number: GPIO2
      inverted: true

    # relay output
  - platform: gpio
    id: relay
    name: $friendly_name
    pin: GPIO4
 
    # automatically make blue led equal relay state
    on_turn_on:
      - if:
          condition: # only if blue LED enabled
            lambda: 'return (id(select_led).state == "Enabled");'
          then:
            switch.turn_on: blue_led

    on_turn_off:
      - switch.turn_off: blue_led

  - platform: restart
    id: restart_switch
    
  - platform: template
    id: clear_wifi_switch
    name: Kauf Plug Clear WiFi Credentials
    optimistic: true
    disabled_by_default: true
#    restore_state: no  # no is default already per https://esphome.io/components/switch/template.html
    on_turn_on:
      then:
        script.execute: clear_wifi_script


# clock input from Home Assistant used to calculate total daily energy
time:
  - platform: homeassistant
    id: homeassistant_time


sensor:   # Power monitoring sensors output to Home Assistant
  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: True
    cf_pin: GPIO5
    cf1_pin: GPIO14
    current_resistor: 0.001 # The value of the shunt resistor for current measurement. 
    voltage_divider: 2401   # The value of the voltage divider on the board as (R_upstream + R_downstream) / R_downstream. 
    power:
      name: ${friendly_name} Power
      unit_of_measurement: W
      id: wattage
      filters:
        - calibrate_linear:
            - 0.0 -> 0.0  
            - 333.8 -> 60 # value with 60W bulb.
      on_value:   # set or clear in_use template binary sensor depending on whether power usage is over threshold
        - if:
            condition:
              lambda: 'return (x >= id(threshold).state);'
            then:
              - binary_sensor.template.publish:
                  id: in_use
                  state: ON
            else:
              - binary_sensor.template.publish:
                  id: in_use
                  state: OFF
    current:
      name: ${friendly_name} Current
      unit_of_measurement: A
      filters:
        - calibrate_linear:
            - 0.0 -> 0.0
            - 0.6 -> 0.515  # value with 60W bulb.
    voltage:
      name: ${friendly_name} Voltage
      unit_of_measurement: V
      filters:
        - calibrate_linear:
            - 0.0 -> 0.0
            - 302.1 -> 117.1 # Tested using a meter
    change_mode_every: 1 
    update_interval: 10s # 20 second effective update rate for Power, 40 second for Current and Voltage.

# Reports the total Power so-far each day, resets at midnight
# See https://esphome.io/components/sensor/total_daily_energy.html
  - platform: total_daily_energy
    name: ${friendly_name} Total Daily Energy
    power_id: wattage
    filters:
        - multiply: 0.001  ## convert Wh to kWh
    unit_of_measurement: kWh


number:      # used as a threshold for whether the plugged-in devices is running.
  - platform: template
    name: ${friendly_name} Use Threshold
    min_value: 1
    max_value: 100
    step: 1
    initial_value: 3
    id: threshold
    optimistic: true     # required for changing value from home assistant
    restore_value: true
    on_value:
      - if:               # set or clear in_use template binary sensor depending on whether power usage is above threshold
          condition:
            lambda: 'return (id(wattage).state >= x);'
          then:
            - binary_sensor.template.publish:
                id: in_use
                state: ON
          else:
            - binary_sensor.template.publish:
                id: in_use
                state: OFF


select:

    # option to disable button
  - platform: template
    name: "Kauf Plug Button"
    id: select_button
    optimistic: true
    options:
      - Enabled
      - Disabled
    initial_option: Enabled
    restore_value: true
    icon: mdi:circle-double


    # option to disable blue LED
  - platform: template
    name: "Kauf Plug LED"
    id: select_led
    optimistic: true
    options:
      - Enabled
      - Disabled
    initial_option: Enabled
    restore_value: true
    icon: mdi:led-on
    on_value:
      then:
      - if:
          condition:
            lambda: 'return ( (id(select_led).state == "Enabled") && id(relay).state );'
          then:
            switch.turn_on: blue_led
          else:
            switch.turn_off: blue_led


# Send IP Address to HA
text_sensor:
  - platform: wifi_info
    ip_address:
      name: $friendly_name IP Address